spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall_tiny?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: password
  redis:
    host: localhost
    database: 0
    port: 6379
    password:
    timeout: 3000ms

logging:
  level:
    root: info
    com.roc.malltiny: debug